---
- name: Demo rules
  hosts: all
  sources:
    - name: azure
      azure_service_bus:
        conn_str: "{{connection_str}}"
        queue_name: "{{queue_name}}"
      transform: jsonify
  rules:
    - name: send to slack
      condition: True
      action:
        slack:
          token: "{{token}}"
          msg: "{{event}}"
